### ISSUE TITLE
Speech to text  

### ISSUE THREAD

**Issue by maximerinna** [ether/ep_text_to_speech#1]
Hello , Mr  McLear 

Are that it is possible to make a Module

Speech to text like the following websites:https://dictation.io/   and     https://speechnotes.co/fr/ in mode continued not stop  recognition

This permetra make EtherPad accesible to the deaf population with WebRTC.

I can call my sister and I can read what it says in EtherPad ..

Best regards ,

**Comment by JohnMcLear** [comment]
Etherpad already has Speech to Text natively.  It has screen reader support.
