### ISSUE TITLE
TTS an STT   screen reader support  

### ISSUE THREAD

**Issue by maximerinna** [ether/ep_text_to_speech#2]
Hello , 

You respond "Etherpad already has **Speech to Text** natively. It has screen reader support."

Can you show me how to use EtherPad with speech to text module. s' Please, for the Screen Module carrier makes reading text but no voice recognition? I'm deaf not blind. ( by a video ? ) 

Thank you for your example of a text pad, I'll say hello, my microphone and display EtherPad hello, I could discuss with my deaf friends at this time.

Not to be confused with the TTS TTS

TTS for the blind
STT for the deaf

Thank you for your help.

**Comment by JohnMcLear** [comment]
Use this plugin: https://www.npmjs.com/package/ep_speechinput :)

**Comment by maximerinna** [comment]
Hello , I tried but no simple solution ...
Can you try like you're deaf? by a test pad?

and the link is ko :  https://www.npmjs.com/package/ep_speechinput

ep_speechinput
Speech Input for Etherpad Lite
_ERROR: No README data found!_

Thank you for your help   How to do ?

MAxime RINNA ( french )

Le mer. 29 juin 2016 à 11:48, John McLear notifications@github.com a
écrit :
